require "valo.plugins.interface.alpha"
require "valo.plugins.interface.bufferline"
require "valo.plugins.interface.indentline"
require "valo.plugins.interface.lualine"
require "valo.plugins.interface.nvim-tree"
require "valo.plugins.interface.treesitter"
require "valo.plugins.interface.gitsigns"
