require "valo.plugins_config.interface.alpha"
require "valo.plugins_config.interface.bufferline"
require "valo.plugins_config.interface.indentline"
require "valo.plugins_config.interface.lualine"
require "valo.plugins_config.interface.nvim-tree"
require "valo.plugins_config.interface.treesitter"
require "valo.plugins_config.interface.gitsigns"
require "valo.plugins_config.interface.marks"
