require "valo.plugins_config.dev.cmp"
require "valo.plugins_config.dev.comment"
require "valo.plugins_config.dev.formatter"
require "valo.plugins_config.dev.hex"
require "valo.plugins_config.dev.trouble"
require "valo.plugins_config.dev.vimtex"
require "valo.plugins_config.dev.lsp"
require "valo.plugins_config.dev.coq"
require "valo.plugins_config.dev.rust-tools"
require "valo.plugins_config.dev.peek"

