require "valo.plugins.dev.comment"
require "valo.plugins.dev.formatter"
require "valo.plugins.dev.hex"
require "valo.plugins.dev.rust-tools"
require "valo.plugins.dev.trouble"
require "valo.plugins.dev.vimtex"
require "valo.plugins.dev.lsp"
require "valo.plugins.dev.coq"
