#!/bin/sh

# set -ex

MOD="Super"
TERMINAL="kitty"
LAUNCHER="rofi -show drun"
KEY_LAYOUT="fr"


riverctl keyboard-layout ${KEY_LAYOUT}

riverctl map normal ${MOD} Q spawn "${TERMINAL}"
riverctl map normal ${MOD} A spawn "${LAUNCHER}"

riverctl map normal ${MOD} J focus-view next
riverctl map normal ${MOD} K focus-view previous
riverctl map normal ${MOD} Z zoom 

riverctl map normal ${MOD}+Shift J swap next
riverctl map normal ${MOD}+Shift K swap previous

riverctl map normal $MOD H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $MOD L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal ${MOD} C close

riverctl map normal ${MOD} F toggle-fullscreen


i=1
keys=("Ampersand" "Eacute" "Quotedbl" "Apostrophe" "Parenleft" "Minus" "Egrave" "Underscore" "Ccedilla")
for key in "${keys[@]}"
do
    tags=$((1 << ($i - 1)))

    # $MOD+[1-9] to focus tag [0-8]
    riverctl map normal $MOD $key set-focused-tags $tags

    # $MOD+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $MOD+Shift $key set-view-tags $tags

    # $MOD+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $MOD+Control $key toggle-focused-tags $tags

    # $MOD+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $MOD+Shift+Control $key toggle-view-tags $tags

    i=$(($i+1))
done

VOLUME_SCRIPT="${XDG_CONFIG_HOME}/river/script/volume.sh"
BRIGHT_SCRIPT="${XDG_CONFIG_HOME}/river/script/brightness.sh"

# Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
riverctl map normal None XF86AudioRaiseVolume  spawn "${VOLUME_SCRIPT}  5"
riverctl map normal None XF86AudioLowerVolume  spawn "${VOLUME_SCRIPT} -5"
riverctl map normal None XF86AudioMute         spawn "${VOLUME_SCRIPT}  0"

riverctl map normal None XF86MonBrightnessUp   spawn "${BRIGHT_SCRIPT}  5"
riverctl map normal None XF86MonBrightnessDown spawn "${BRIGHT_SCRIPT} -5"

# Set background and border color
riverctl background-color 0x28282800
riverctl border-color-focused 0xa89984ff
riverctl border-color-unfocused 0x28282800

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

